name: Release Pipeline

on:
  push: {}

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dotnet tools
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Blablabla
        run: |
          echo "Mr."
          echo "Freeman"

      - name: Run Core.Test
        run: dotnet test .\src\DevOpsDaysTasks.Tests

      - name: Run Integrations.Test
        run: dotnet test .\src\DevOpsDaysTasks.IntegrationTests